version: '3.8'
services: 
  web:
    build:  
      context: .    
      dockerfile: Dockerfile 
    command: python ./__init__.py
    environment: 
      FLASK_APP: __init__.py
      FLASK_DEBUG: 1
    ports: 
      - 80:5000
    volumes: 
      - ./:/usr/src/app

  redis:
      image: redis:6-alpine
      command: redis-server --requirepass sOmE_sEcUrE_pAsS 
      ports: 
        - 6379:6379
      volumes:
        - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
      environment:
        - REDIS_REPLICATION_MODE=master
